### ISSUE TITLE
растянуть кнопку "Купить"

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/rybolove#101]
![image](https://cloud.githubusercontent.com/assets/11739563/8013811/7613681a-0bd4-11e5-8678-2b3a47971f53.png)

**Comment by Wilvarin** [comment]
![image](https://cloud.githubusercontent.com/assets/11726090/8013862/aeee5596-0bd4-11e5-86ef-7801f0925cc6.png)
у меня вот так

**Comment by Wilvarin** [comment]
саня сделал
