### ISSUE TITLE
неодинаковый отступ в футере моб версия

### ISSUE THREAD

**Issue by dadakax** [TopQualityGuys/rybolove#104]
![image](https://cloud.githubusercontent.com/assets/8439283/8014368/bf0b3bac-0bd8-11e5-8dd8-5af55415a5c6.png)

**Comment by dadakax** [comment]
почему эта задача закрыта, хотя на самом деле она не сделана?!
![image](https://cloud.githubusercontent.com/assets/8439283/8090156/fcc2a2de-0fb4-11e5-8741-9b5a13c4d66f.png)

**Comment by Wilvarin** [comment]
![image](https://cloud.githubusercontent.com/assets/11726090/8090660/1babad6e-0fb8-11e5-8142-fd3493bb7e6c.png)

**Comment by dadakax** [comment]
![image](https://cloud.githubusercontent.com/assets/8439283/8090828/f55b6af4-0fb8-11e5-91e9-d856f3185677.png)

**Comment by Wilvarin** [comment]
![image](https://cloud.githubusercontent.com/assets/11726090/8090998/a730cf08-0fb9-11e5-8667-9e6f3bae4093.png)
