### ISSUE TITLE
Выровнять картинки по ширине блока товара

### ISSUE THREAD

**Issue by nikolayr1** [TopQualityGuys/rybolove#106]
Когда у товара нет картинки то изображение 190х150 смещается влево
![image](https://cloud.githubusercontent.com/assets/11279857/8014429/591d898e-0bd9-11e5-8d63-12880be3c78d.png)

**Comment by dadakax** [comment]
по центру их поставь прост

**Comment by nikolayr1** [comment]
как ?

**Comment by nikolayr1** [comment]
margin 0 auto или text-align center не работают

**Comment by dadakax** [comment]
ща сделаю

**Comment by dadakax** [comment]
чет я пока не шарю как это сделать)) если кто-то раз
