### ISSUE TITLE
сделать что бы отсчет шел от 1 

### ISSUE THREAD

**Issue by Wilvarin** [TopQualityGuys/rybolove#109]
![image](https://cloud.githubusercontent.com/assets/11726090/8015510/d433106e-0be1-11e5-80e2-87b79064bea2.png)

**Comment by dadakax** [comment]
надо кароче запретить вводить все кроме цифр

**Comment by Wilvarin** [comment]
я думаю это саня сделает 
он уже как-то делал

**Comment by AndruAlex** [comment]
Я уже завтра ее буду делать или послезавтра!

**Comment by AndruAlex** [comment]
блин там стоит ограничение но я не знаю какой человек будет специально впичівать -1

**Comment by dadakax** [comment]
просто мало ли, случайно символ нажал и все. ну не должно такого быть
