### ISSUE TITLE
убрать кнопки отображения товаров (списком, картинками)

### ISSUE THREAD

**Issue by dumbik** [TopQualityGuys/rybolove#112]
![image](https://cloud.githubusercontent.com/assets/11014944/8024189/2c6c3150-0d33-11e5-9fc1-d77faac50d2b.png)

**Comment by dadakax** [comment]
Да. Убрать их

**Comment by Wilvarin** [comment]
долой эти кнопки.

**Comment by nikolayr1** [comment]
имхо, на телефонах намного удобнее смотреть товары списком. я за то, чтобы их оставить

**Comment by dadakax** [comment]
Так на телефоне они все в одну колонку и так
