### ISSUE TITLE
IE: картинки в слайдере популярных товаров вылазят за блок

### ISSUE THREAD

**Issue by dumbik** [TopQualityGuys/rybolove#114]
![image](https://cloud.githubusercontent.com/assets/11014944/8024255/44652b38-0d36-11e5-8f8b-9faabb62f409.png)

**Comment by Wilvarin** [comment]
![image](https://cloud.githubusercontent.com/assets/11726090/8033780/fb2c8024-0de9-11e5-93ad-6483539e0463.png)
complet
