### ISSUE TITLE
IE: кнопки "купить" и "подбробнее" разной ширины в популярных товарах

### ISSUE THREAD

**Issue by dumbik** [TopQualityGuys/rybolove#115]
![image](https://cloud.githubusercontent.com/assets/11014944/8024271/7e81f7c4-0d36-11e5-90c1-4b69df3bc527.png)

**Comment by Wilvarin** [comment]
![image](https://cloud.githubusercontent.com/assets/11726090/8031849/515c0740-0dda-11e5-983d-cb6f94dc6699.png)
сделал их 1 ширины. 
но в ИЕ не подключаются шрифты и потому "подробнее" не влазит в кнопку =(
![image](https://cloud.githubusercontent.com/assets/11726090/8032021/8ee449be-0ddb-11e5-8c91-7b2c1c2f011d.png)

**Comment by Wilvarin** [comment]
![image](https://cloud.githubusercontent.com/assets/11726090/8032492/e9b680b6-0dde-11e5-9dd2-4374ba2a98d2.png)
такс. все влазит)

**Comment by Wilvarin** [comment]
можно закрывать эту задачу и переходить к следующей? https://github.com/TopQualityGuys/rybolove/issues/114
