### ISSUE TITLE
IE: блоки популярных товаров разной высоты

### ISSUE THREAD

**Issue by dumbik** [TopQualityGuys/rybolove#116]
![image](https://cloud.githubusercontent.com/assets/11014944/8024280/ab1545b6-0d36-11e5-8b36-508aca68180d.png)

**Comment by Wilvarin** [comment]
![image](https://cloud.githubusercontent.com/assets/11726090/8033785/0b2f5500-0dea-11e5-9bc4-7558db14f19f.png)
complet
