### ISSUE TITLE
IE: исчезают некоторые пункты меню при масштабировании (не уменьшается шрифт)

### ISSUE THREAD

**Issue by dumbik** [TopQualityGuys/rybolove#118]
![image](https://cloud.githubusercontent.com/assets/11014944/8024351/d76a529e-0d38-11e5-978b-378f2276e63c.png)

**Comment by Wilvarin** [comment]
![image](https://cloud.githubusercontent.com/assets/11726090/8033823/682a721c-0dea-11e5-8b7f-3da4657ab83b.png)
не исчезают. все упирается в шрифт
