### ISSUE TITLE
IE: содержимое страницы прыгает вправо, как и слайдер на главной странице, при масштабировании страницы

### ISSUE THREAD

**Issue by dumbik** [TopQualityGuys/rybolove#119]
![image](https://cloud.githubusercontent.com/assets/11014944/8024361/327484c0-0d39-11e5-9b19-02b7ab3ad3d6.png)

**Comment by Wilvarin** [comment]
не торопитесь это править. 
оно улетает из-за того что из меню падают 2 последних пункта. 
поправим меню и эта задача исчезнет.
