### ISSUE TITLE
"доставка по всей украине"

### ISSUE THREAD

**Issue by dumbik** [TopQualityGuys/rybolove#123]
надпись пропадает при изменении размеров окна браузера
![image](https://cloud.githubusercontent.com/assets/11014944/8024440/93fb4852-0d3c-11e5-8170-d96fd519450f.png)

**Comment by Wilvarin** [comment]
![image](https://cloud.githubusercontent.com/assets/11726090/8055018/62b5b3ee-0ea5-11e5-8f06-b14dbf942826.png)
![image](https://cloud.githubusercontent.com/assets/11726090/8055081/b58ba74a-0ea5-11e5-9703-9ff1a403f4e3.png)
