### ISSUE TITLE
размер картинки товара на странице товара (мобильная версия). как по мне - нужно ее уменьшить

### ISSUE THREAD

**Issue by dumbik** [TopQualityGuys/rybolove#125]
Оля, что скажешь? или другие

**Comment by olleskiv** [comment]
Да, лучше сделать в два столбика хотя бы

**Comment by Wilvarin** [comment]
Оль, это страница товара, там всего 1 товар. 
Мы просто уменьшим размер картинки.

**Comment by Wilvarin** [comment]
обсудили с Антоном, все там норм)
