### ISSUE TITLE
В фильтрах поровнять блоки

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/rybolove#126]
![image](https://cloud.githubusercontent.com/assets/11739563/8024826/a2eb19fc-0d49-11e5-8436-0dbd52fdc874.png)

**Comment by Wilvarin** [comment]
![image](https://cloud.githubusercontent.com/assets/11726090/8025110/f4348c22-0d52-11e5-93bd-c83102afe6fd.png)
