### ISSUE TITLE
Капризы художников

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/rybolove#128]
Поставить блок гарантии перед помощью
![image](https://cloud.githubusercontent.com/assets/11739563/8024885/4759eb6a-0d4c-11e5-8bf2-a7c1300564fc.png)

**Comment by Wilvarin** [comment]
![image](https://cloud.githubusercontent.com/assets/11726090/8025008/6fb62e62-0d50-11e5-8854-a45a4f36aa67.png)
