### ISSUE TITLE
поменять цвет кнопки купить 

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/rybolove#129]
#57aa3c
![3](https://cloud.githubusercontent.com/assets/11739563/8024946/021b3dae-0d4e-11e5-9740-abe29cf00307.png)

**Comment by Wilvarin** [comment]
![image](https://cloud.githubusercontent.com/assets/11726090/8024994/02472016-0d50-11e5-824b-df377a29c774.png)
complet
