### ISSUE TITLE
Убрать кнопку описания в просмотре товаров

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/rybolove#130]
Сделать блоки купить и описание в один ряд и одной длинны, так, как это в шаблоне
![image](https://cloud.githubusercontent.com/assets/11739563/8024954/be90adca-0d4e-11e5-8ac6-9f3fc9916569.png)
![3](https://cloud.githubusercontent.com/assets/11739563/8024955/c16c0166-0d4e-11e5-8061-b7ea6c2fe3ec.png)

**Comment by dadakax** [comment]
а поле с единичкой куда засунуть в таком случае?

**Comment by olleskiv** [comment]
Туда же 
![4](https://cloud.githubusercontent.com/assets/11739563/8025187/100944ea-0d55-11e5-8bfc-65d073296011.png)

**Comment by dadakax** [comment]
в шаблоне совсем не так
![image](https://cloud.githubusercontent.com/assets/8439283/8025420/007e1e92-0d5f-11e5-80f1-46cae34718b5.png)
Я считаю, что описание должно быть ниже, так как это не кнопка, а заголовок

**Comment by Wilvarin** [comment]
я уже писал что это заголовок. 
и в дальнейшем у нас еще будут коментарии => и описание станет кнопкой)

**Comment by dadakax** [comment]
Согласна с Юрой

**Comment by olleskiv** [comment]
тогда пока слово описание можно вообще убрать

Что думаете по этому поводу?

**Comment by dadakax** [comment]
Да, убрать можно

**Comment by dadakax** [comment]
![image](https://cloud.githubusercontent.com/assets/8439283/8041728/f454bd78-0e22-11e5-83aa-40bc8dcf96d7.png)
