### ISSUE TITLE
Мобильная версия меню: надпись каталог товаров по центру, кнопку фильтров оставить только на страницах категорий и поиска

### ISSUE THREAD

**Issue by dadakax** [TopQualityGuys/rybolove#131]
![image](https://cloud.githubusercontent.com/assets/8439283/8042873/de84e3b2-0e2a-11e5-9731-7e6866ea7d73.png)

**Comment by dadakax** [comment]
вообще не сделано

**Comment by successus** [comment]
Назва задачі повинна бути назвою задачі. Декілька слів достатньо. 
Для опису є опис. 

(Капітан очевидність)
