### ISSUE TITLE
ie: страница категорий

### ISSUE THREAD

**Issue by dadakax** [TopQualityGuys/rybolove#133]
![image](https://cloud.githubusercontent.com/assets/8439283/8043997/534668b8-0e32-11e5-83f6-857189f10657.png)

**Comment by Wilvarin** [comment]
![image](https://cloud.githubusercontent.com/assets/11726090/8053302/f206d162-0e97-11e5-995f-e28a2ec5cd7c.png)
![image](https://cloud.githubusercontent.com/assets/11726090/8053304/f87f640a-0e97-11e5-8537-a8e2aadc20b4.png)
