### ISSUE TITLE
добавить отступ от меню "хлебных крошек" (страница товара) в разрешении для планшета

### ISSUE THREAD

**Issue by dumbik** [TopQualityGuys/rybolove#135]
![image](https://cloud.githubusercontent.com/assets/11014944/8053610/fad2d64e-0e9a-11e5-852a-93dc1cd68eb3.png)

**Comment by Wilvarin** [comment]
![image](https://cloud.githubusercontent.com/assets/11726090/8053975/be292538-0e9d-11e5-822c-70fd54f433b4.png)
complet
