### ISSUE TITLE
Катушки?

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/rybolove#139]
Мне кажется, не надо в каждом пункте повторять слово "Катушки". Что думаете?
![image](https://cloud.githubusercontent.com/assets/11739563/8056805/6d637196-0eb4-11e5-9122-bd85c640949a.png)

**Comment by olleskiv** [comment]
То же самое 
![image](https://cloud.githubusercontent.com/assets/11739563/8056815/8d95cfc2-0eb4-11e5-9e5b-da81dcdc05a4.png)

**Comment by dadakax** [comment]
та не, по-моему норм
а то будет например просто серфовые. А что серфовые не понятно
нужно так и оставлять

**Comment by nikolayr1** [comment]
согласен с Дашей

**Comment by AndruAlex** [comment]
даша +
