### ISSUE TITLE
Растянуть кнопку купить и количества товаров

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/rybolove#140]
![23](https://cloud.githubusercontent.com/assets/11739563/8056907/6eb65120-0eb5-11e5-852c-edf1c87d4639.png)

**Comment by AndruAlex** [comment]
блиин оль зачем в шаблоне совсем не так

**Comment by Wilvarin** [comment]
для сравнения 
![image](https://cloud.githubusercontent.com/assets/11726090/8070119/bd646120-0f07-11e5-9d9c-23e8281616a3.png)
![image](https://cloud.githubusercontent.com/assets/11726090/8070122/c46bc3aa-0f07-11e5-950c-05d1f31c2481.png)

**Comment by dumbik** [comment]
закрываю. вариант как в шаблоне норм, этот - нет. это писала не Оля если что
