### ISSUE TITLE
Сделать верхний отступ такой, как и нижний

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/rybolove#143]
Стрница уже купленного товара
![image](https://cloud.githubusercontent.com/assets/11739563/8057147/76fc397e-0eb7-11e5-992f-c5f9ee0ee2f9.png)

**Comment by Wilvarin** [comment]
![image](https://cloud.githubusercontent.com/assets/11726090/8069996/f26800ee-0f06-11e5-8444-5e1e37e16186.png)
