### ISSUE TITLE
В мобильной версии не работает кнопка фильтров справа

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/rybolove#151]
![image](https://cloud.githubusercontent.com/assets/11739563/8057455/13a1c3a0-0eba-11e5-80be-f1dc5ebca692.png)

**Comment by Wilvarin** [comment]
еще не доделал Саня корректно

**Comment by AndruAlex** [comment]
так во первых она не бдет никак работать на главной странице (и всех статических)
из за того что там нет товаров - отсюда вопрос нужна ли она вообще?
