### ISSUE TITLE
Корзина в корзине :)

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/rybolove#154]
![image](https://cloud.githubusercontent.com/assets/11739563/8057560/0396abaa-0ebb-11e5-8eed-adaa4c6c97be.png)

**Comment by AndruAlex** [comment]
А как маленькая корзина рендерится в маин лайаут 
ты кароче ни каак не сможешь убрать !

**Comment by AndruAlex** [comment]
корзину
