### ISSUE TITLE
Вернуть высоту у блоков "с дешевых/дорогих" и количества товаров на странице

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/rybolove#158]
Поставить высоту где-то в один размер со шрифтом
![image](https://cloud.githubusercontent.com/assets/11739563/8088094/9bd8477e-0fa7-11e5-9583-6b83d574c5fb.png)

**Comment by Wilvarin** [comment]
![image](https://cloud.githubusercontent.com/assets/11726090/8089657/e83e81be-0fb1-11e5-8c40-e5fd8f70a9d3.png)
