### ISSUE TITLE
расстянуть кнопку купить в два раза

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/rybolove#159]
![image](https://cloud.githubusercontent.com/assets/11739563/8088155/ee3fbe70-0fa7-11e5-940a-8b387c6d5df3.png)

**Comment by Wilvarin** [comment]
![image](https://cloud.githubusercontent.com/assets/11726090/8089586/5b49b814-0fb1-11e5-89e2-e0520bc4c729.png)
