### ISSUE TITLE
Адаптивная верстка до 24.05.2015 23.59

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/rybolove#16]
Сверстать для 4 разрешений

1) для разрешений от 1200 пикселей и больше:
![1200](https://cloud.githubusercontent.com/assets/11739563/7708459/7c2e095e-fe5e-11e4-9015-4d365d7b231b.png)

**Comment by olleskiv** [comment]
2) от 992 до 1200 пикселей 
![992](https://cloud.githubusercontent.com/assets/11739563/7709458/db6b43f8-fe65-11e4-92db-4f135491d3cd.png)

**Comment by olleskiv** [comment]
3) от 768 до 992 пикселей 
![768](https://cloud.githubusercontent.com/assets/11739563/7727798/f2285118-ff13-11e4-80d2-ff214cce6a64.png)

**Comment by olleskiv** [comment]
4) Меньше 768, ориентированно на 600 пикселей
![600](https://cloud.githubusercontent.com/assets/11739563/7736867/895dcfd2-ff4f-11e4-92e1-0a3ab04079d1.png)

**Comment by dadakax** [comment]
![image](https://cloud.githubusercontent.com/assets/8439283/7758809/27b46f86-0015-11e5-9fa2-5314f45db610.png)

**Comment by dadakax** [comment]
![image](https://cloud.githubusercontent.com/assets/8439283/7759238/66471a34-0018-11e5-9bcc-d90a6511b98d.png)

**Comment by dadakax** [comment]
То, что не сделано еще открыто в отдельных задачах
