### ISSUE TITLE
Каталог товаров(моб верися)

### ISSUE THREAD

**Issue by Wilvarin** [TopQualityGuys/rybolove#160]
пофиксить уплывание текста 
![image](https://cloud.githubusercontent.com/assets/11726090/8089847/05d770f4-0fb3-11e5-87b1-fd5b9ad14329.png)

**Comment by dadakax** [comment]
паддинг левый поставь

**Comment by Wilvarin** [comment]
там все гораздо проще )
посмотришь в коммите
