### ISSUE TITLE
Моб меню. Сделать отступ слева 10-20 пикселей? 

### ISSUE THREAD

**Issue by Wilvarin** [TopQualityGuys/rybolove#161]
или вообще по центру выровнять? 
![image](https://cloud.githubusercontent.com/assets/11726090/8089990/e5782ad2-0fb3-11e5-932d-a8b3b13ec136.png)

**Comment by dadakax** [comment]
мне кажется лучше текст по центру сделать

**Comment by Wilvarin** [comment]
![image](https://cloud.githubusercontent.com/assets/11726090/8090383/525329b6-0fb6-11e5-8d52-bfbc9fa0bca3.png)
