### ISSUE TITLE
корзина моб 

### ISSUE THREAD

**Issue by dadakax** [TopQualityGuys/rybolove#162]
![image](https://cloud.githubusercontent.com/assets/8439283/8093544/6a27888e-0fca-11e5-8387-5b3eb0677828.png)

**Comment by Wilvarin** [comment]
сейчас пошаманю.

**Comment by Wilvarin** [comment]
в моб версии решил убрать кнопки "+-", достаточно удобно просто клацать на поле и вводить число 
![image](https://cloud.githubusercontent.com/assets/11726090/8113396/7cd94c0e-1076-11e5-892b-e08c36df52f4.png)
