### ISSUE TITLE
нельзя оформить заказ когда незалогинился

### ISSUE THREAD

**Issue by dadakax** [TopQualityGuys/rybolove#163]
![image](https://cloud.githubusercontent.com/assets/8439283/8093590/b08e3c46-0fca-11e5-8c1c-50ad9f5ae558.png)

**Comment by Wilvarin** [comment]
нельзя оформить не указав mail

**Comment by dadakax** [comment]
Добавила обязательный имеил обратно
![image](https://cloud.githubusercontent.com/assets/8439283/8116204/54bc2328-1089-11e5-85d0-2a20e134fbe4.png)

![image](https://cloud.githubusercontent.com/assets/8439283/8116235/8af03eca-1089-11e5-8073-2f1e8413725d.png)
