### ISSUE TITLE
Может все-таки вставить какую-то картиночку на главную в мобильной версии? 

### ISSUE THREAD

**Issue by dadakax** [TopQualityGuys/rybolove#164]
![image](https://cloud.githubusercontent.com/assets/8439283/8093680/2b26f9fc-0fcb-11e5-8df1-c92812863db2.png)
А то без слайдера как-то уныло

**Comment by Wilvarin** [comment]
вставить

**Comment by olleskiv** [comment]
да, конечно вставить
Можно только одну большую вставить
Или три маленькие квадратом
Все четыре не надо

**Comment by Wilvarin** [comment]
убрал самую большую картинку. Оставил квадратик маленьких. 
![image](https://cloud.githubusercontent.com/assets/11726090/8112475/7ccc31b4-1070-11e5-9604-e1ea68bc4ab4.png)
