### ISSUE TITLE
Поиск.

### ISSUE THREAD

**Issue by Wilvarin** [TopQualityGuys/rybolove#165]
перевести сообщение "no results found"
![image](https://cloud.githubusercontent.com/assets/11726090/8093953/bee7ed3a-0fcc-11e5-82eb-8d279d82ef8e.png)

**Comment by AndruAlex** [comment]
![image](https://cloud.githubusercontent.com/assets/11726264/8113290/a691cea0-1075-11e5-9b1e-6218b41f2f2f.png)

**Comment by dadakax** [comment]
нужно сделать по-другому

**Comment by AndruAlex** [comment]
и так покатит)пока что ))
а потом переделаю)

**Comment by AndruAlex** [comment]
Все готово
![image](https://cloud.githubusercontent.com/assets/11726264/8117457/de33c410-1090-11e5-9b58-6d87cef07116.png)
