### ISSUE TITLE
Фильтр цены

### ISSUE THREAD

**Issue by nikolayr1** [TopQualityGuys/rybolove#167]
при изменении положения ползунка в фильтре цены значения цены не появляются в соответствующих полях
![image](https://cloud.githubusercontent.com/assets/11279857/8095963/ea928342-0fda-11e5-9790-155b9a2ffcb2.png)
есть подозрения, что эта проблема связана с #173

**Comment by nikolayr1** [comment]
бред в том, что в мобильной версии цифры работают
![image](https://cloud.githubusercontent.com/assets/11279857/8119117/e104fc76-109b-11e5-9696-5634b6853b12.png)

**Comment by Wilvarin** [comment]
знаем. 
бред.

**Comment by nikolayr1** [comment]
пофиксено
![image](https://cloud.githubusercontent.com/assets/11279857/8119312/4dffa91a-109d-11e5-8bbd-9524c96ccfa3.png)

**Comment by nikolayr1** [comment]
а, нет. хм. интересная задача

**Comment by nikolayr1** [comment]
я понял, что если виджет грузится дважды на странице, то последний не будет работать

**Comment by dadakax** [comment]
последний не будет работать скорее всего из-за одинаковых айдишек
посмотри в доках по jquery-ui как подключается этот слайдер и просто подключи один из них с другими айдишками

**Comment by nikolayr1** [comment]
сделано. фильтры для мобильных устройств не работают только на мобильных устройствах и планшетах

**Comment by Wilvarin** [comment]
шта?

**Comment by nikolayr1** [comment]
если ты будешь сужать окно браузера на компе то фильтры для мобильных устройств не появятся.
