### ISSUE TITLE
Оптимізація. Включити кешування.

### ISSUE THREAD

**Issue by successus** [TopQualityGuys/rybolove#170]
Розбиріться із кешуванням. Подивіться як його можна включити. І які розділи

**Comment by AndruAlex** [comment]
http://ruhighload.com/post/%D0%9E%D0%BF%D1%82%D0%B8%D0%BC%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F+YII
Стас нам по максимуму закешировать ?
используя все доступные методы?

**Comment by dadakax** [comment]
![image](https://cloud.githubusercontent.com/assets/8439283/8119143/05697344-109c-11e5-804f-8ce1b9972b49.png)
![image](https://cloud.githubusercontent.com/assets/8439283/8119148/0f55eef0-109c-11e5-9696-dd7b7ce09e38.png)

**Comment by dadakax** [comment]
![image](https://cloud.githubusercontent.com/assets/8439283/8120195/4e4adb94-10a5-11e5-8757-02628e6af869.png)
