### ISSUE TITLE
Не выключается мобильные фильтры

### ISSUE THREAD

**Issue by nikolayr1** [TopQualityGuys/rybolove#173]
при первоначальном сужении экрана до ширины мобильного устройства и последующего его расширении до исходной ширины мобильная версия фильтров не пропадает.
![image](https://cloud.githubusercontent.com/assets/11279857/8118222/61abce96-1096-11e5-96bd-2c67f828ea27.png)
есть подозрения, что эта проблема связана с #167 .

**Comment by Wilvarin** [comment]
Коль, удали эту задачу.

**Comment by nikolayr1** [comment]
ну ок. здравое замечание
