### ISSUE TITLE
Левый файл jquery подключается непонятно откуда. убрать

### ISSUE THREAD

**Issue by dadakax** [TopQualityGuys/rybolove#174]
![image](https://cloud.githubusercontent.com/assets/8439283/8120343/c076329e-10a6-11e5-8fa8-b0cfee6c0e5b.png)

**Comment by nikolayr1** [comment]
хм. нашел только подлючения <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

**Comment by AndruAlex** [comment]
Коля єто кеш 
єто то что загружаеться в кеш браузера
