### ISSUE TITLE
Популярные товары. 

### ISSUE THREAD

**Issue by Wilvarin** [TopQualityGuys/rybolove#175]
вот так вот оно выглядит на сервере. 
![image](https://cloud.githubusercontent.com/assets/11726090/8128045/4a4d67c8-1104-11e5-85d7-1679f1ac3a2b.png)
а на локальном все ок. причем что код один и тот же, я проверил 
![image](https://cloud.githubusercontent.com/assets/11726090/8128074/7dc07fc8-1104-11e5-92d8-6666a68c3f98.png)

**Comment by dadakax** [comment]
Что-то я не могу понять что не так...

**Comment by dadakax** [comment]
А, все, поняла

**Comment by Wilvarin** [comment]
расскажешь что там мешало или чего не хватало.

**Comment by nikolayr1** [comment]
все работает
![image](https://cloud.githubusercontent.com/assets/11279857/8149001/d107c870-12bd-11e5-879a-494e29a9e007.png)
