### ISSUE TITLE
Кнопка для прокрутки наверх

### ISSUE THREAD

**Issue by dadakax** [TopQualityGuys/rybolove#178]
Неплохо было бы на всех страницах кнопку для прокрутки наверх прикрутить

**Comment by nikolayr1** [comment]
я припилю))

**Comment by nikolayr1** [comment]
![image](https://cloud.githubusercontent.com/assets/11279857/8148982/55d9a470-12bd-11e5-99ee-5deb0ff9b421.png)

**Comment by dadakax** [comment]
а вдруг Оля дизайн другой захочет?)

**Comment by Wilvarin** [comment]
точно захочет)
