### ISSUE TITLE
Выравнивание картинки 

### ISSUE THREAD

**Issue by nikolayr1** [TopQualityGuys/rybolove#179]
Нужно сделать центральное ровнение для картинки отсутствия фотографии товара
![image](https://cloud.githubusercontent.com/assets/11279857/8149051/ba1ae19a-12bf-11e5-91bf-5a7ecc463cf4.png)

**Comment by Wilvarin** [comment]
https://github.com/TopQualityGuys/rybolove/issues/110
вот что получается если сделать эту задачу. в скором времени я надеюсь что будут все картинки и все будет ок.

**Comment by nikolayr1** [comment]
ну ок. тогда охрана отмена
