### ISSUE TITLE
Адаптивная верстка корзины до 24.05.2015 23.59

### ISSUE THREAD

**Issue by Wilvarin** [TopQualityGuys/rybolove#18]
![image](https://cloud.githubusercontent.com/assets/11726090/7730715/8a4e7264-ff24-11e4-94cc-517e1252b4a3.png)

**Comment by Wilvarin** [comment]
![image](https://cloud.githubusercontent.com/assets/11726090/7781175/540b0a1c-00f2-11e5-91c7-108f8e40973d.png)
![image](https://cloud.githubusercontent.com/assets/11726090/7781179/603cb588-00f2-11e5-8535-4ca136a51f47.png)
![image](https://cloud.githubusercontent.com/assets/11726090/7781180/651077e8-00f2-11e5-80e6-9d5d3fd748c0.png)

**Comment by dadakax** [comment]
![image](https://cloud.githubusercontent.com/assets/8439283/7782899/e67734d2-0135-11e5-9dcd-fa1fb8eab326.png)

**Comment by dadakax** [comment]
Даже на твоих скринах полоса прокрутки есть
И то что нет бокового меню, это так надо?

**Comment by dadakax** [comment]
![image](https://cloud.githubusercontent.com/assets/8439283/7782906/4bab1062-0136-11e5-9749-bc7b592b32a4.png)

**Comment by dadakax** [comment]
И вообще, по поводу этих форм у Оли проконсультироваться надо, чет они мне по виду не очень нравятся

**Comment by Wilvarin** [comment]
А зачем меню в корзине? 
Полоса прокрутки из-за хедера, что в нем выпирает.

**Comment by dadakax** [comment]
А вдруг человек посмотрит на корзину и захочет еще что-то купить?

**Comment by nikolayr1** [comment]
я думаю, что меню категорий не нужно в корзине

**Comment by olleskiv** [comment]
категории не нужны, если захотят вернуться в магаз, нажмут на лого

Версия для 320 пикселей корзины. Три нижних блока, думаю, очевидны
![320](https://cloud.githubusercontent.com/assets/11739563/7785220/525db68c-018e-11e5-9f15-7d5ca7d05ba7.png)

**Comment by dadakax** [comment]
убрать корзину в корзине)
