### ISSUE TITLE
Пустой поиск

### ISSUE THREAD

**Issue by nikolayr1** [TopQualityGuys/rybolove#182]
если нажать на кнопку ПОИСК и в строке поиска не будет поисковой фразы, то сайт ломается.
![image](https://cloud.githubusercontent.com/assets/11279857/8237606/47a7d392-15f9-11e5-9df5-68fc6ad8c009.png)

**Comment by successus** [comment]
Рядок 100 в www/protected/modules/store/controllers/CategoryController.php
Там потрібно зробити перевірку якісну.

**Comment by nikolayr1** [comment]
![image](https://cloud.githubusercontent.com/assets/11279857/8452974/87bc36b8-1ff8-11e5-93d5-92ef333240ca.png)
