### ISSUE TITLE
позиционирование меню в мобильной версии

### ISSUE THREAD

**Issue by dumbik** [TopQualityGuys/rybolove#184]
можешь сделать фиксированное положение сверху?
![image](https://cloud.githubusercontent.com/assets/11014944/8242363/7e732d36-1617-11e5-999d-7906f6a1776a.png)

**Comment by nikolayr1** [comment]
да, кнопочку КАТАЛОГ ТОВАРОВ было бы неплохо закрепить сверху

**Comment by dumbik** [comment]
но с другой стороны у нас "для этого" есть кнопочка "вверх"

**Comment by Wilvarin** [comment]
не стоит закреплять меню в моб. версии, мое мнение.
