### ISSUE TITLE
исправить битые ссылки

### ISSUE THREAD

**Issue by dumbik** [TopQualityGuys/rybolove#185]
скорее всего дело в картинках

**Comment by nikolayr1** [comment]
список битых ссылок:
http://rybolove.com.ua/primanki/page/164
http://rybolove.com.ua/primanki/page/43
http://rybolove.com.ua/primanki/page/59
http://rybolove.com.ua/primanki/silikonovie-primanki/page/43
http://rybolove.com.ua/primanki/silikonovie-primanki/page/58
http://rybolove.com.ua/primanki/vobleri/page/30
и еще есть эта:
http://rybolove.com.ua/uploads/product/cfoto.php.jpg

**Comment by dumbik** [comment]
ссылки не важны. коля, оставь эту задачу, я сам ее решу
