### ISSUE TITLE
текст главной страницы

### ISSUE THREAD

**Issue by nikolayr1** [TopQualityGuys/rybolove#189]
поставить текст на главной странице. это очень важно для сео.

**Comment by nikolayr1** [comment]
я запилил временный текст. Оля, как он выглядит? что по дизайну?

**Comment by olleskiv** [comment]
мне кажется, что текст лучше вставить так 
![28](https://cloud.githubusercontent.com/assets/11739563/8294802/90ed5e4a-1947-11e5-842c-7f53779590af.png)

**Comment by olleskiv** [comment]
даже вот тк лучше 
![29](https://cloud.githubusercontent.com/assets/11739563/8295001/450f210a-1949-11e5-8d01-daf0ffcde5ca.png)
