### ISSUE TITLE
Личный кабинет адаптивная верстка до 24.05.2015 23.59

### ISSUE THREAD

**Issue by dadakax** [TopQualityGuys/rybolove#19]
![image](https://cloud.githubusercontent.com/assets/8439283/7746441/f51baf44-ffba-11e4-8efc-d9e3a99238fd.png)

**Comment by Wilvarin** [comment]
![image](https://cloud.githubusercontent.com/assets/11726090/7780928/32716616-00ee-11e5-84ef-f4a0b19e1965.png)

**Comment by dadakax** [comment]
![image](https://cloud.githubusercontent.com/assets/8439283/7782889/73f807ba-0135-11e5-9f21-694d0d40e2be.png)

**Comment by dadakax** [comment]
И то, что в нет бокового меню, это так задумано?

**Comment by Wilvarin** [comment]
хедер стал лучше и лк тоже 
![image](https://cloud.githubusercontent.com/assets/11726090/7785074/5a9f4190-0188-11e5-8570-9b656ea513e8.png)

**Comment by dadakax** [comment]
![image](https://cloud.githubusercontent.com/assets/8439283/7785373/c3f5c2f6-0195-11e5-8afd-d9d985b42c39.png)

**Comment by Wilvarin** [comment]
![image](https://cloud.githubusercontent.com/assets/11726090/7785698/b254371c-01a4-11e5-8358-9bfb9b99247a.png)
