### ISSUE TITLE
Keywords и Description

### ISSUE THREAD

**Issue by nikolayr1** [TopQualityGuys/rybolove#191]
Для каждого товара нужно указать Keywords и Description
Вот эти поля в админке
![image](https://cloud.githubusercontent.com/assets/11279857/8453300/0ac7f850-1ffc-11e5-91c0-3c5dd65fe7ff.png)
сейчас на сайте нет этих мета тегов ни в одном товаре и поисковик видет все так:
![image](https://cloud.githubusercontent.com/assets/11279857/8453344/5faee3c4-1ffc-11e5-975f-431b5f2b1d9e.png)
Это очень кончено, особенно если у товара нет описания.
Добавить эти поля нужно в бд.

**Comment by dumbik** [comment]
в чем отличие meta_keywords от meta_description? и meta_description от description?
на странице товара будут отображаться как-то meta_keywords и meta_description?

**Comment by nikolayr1** [comment]
<b>meta_keywords</b> - ключевые слова для поисковика. пользователь их не видит. <i>5-10 слов.</i>
<b>meta_description</b> - описание для поисковика. пользователь видит на странице результатах поиска в поисковике после жирной ссыкли на страницу. на самом сайте пользователь meta_description не видит.<i>10-30 слов</i>
<b>description</b> - описание товара. его видит пользователь. <i>250 и больше слов</i>

**Comment by dumbik** [comment]
сделано и залито
