### ISSUE TITLE
Описания товаров

### ISSUE THREAD

**Issue by nikolayr1** [TopQualityGuys/rybolove#192]
Для каждого товара нужно сделать описание. Намного лучше будет даже иметь однотипное описание на 1.5к символов, чем не иметь вообще никакого текста на странице.
Описания храняться в таблице items_for_rybolove.
![image](https://cloud.githubusercontent.com/assets/11279857/8453438/535e7fa2-1ffd-11e5-8e42-9ef7f1c77d3c.png)
В поле opisanie нужно вставить что-то типа такого текста:
"$productName - это качественная $categoryName которую хотел бы купить каждый рыбак. Только в интернет-магазине rybolove.com.ua вы можете дешево <b>купить $productName. </b> тролололо." 
Кароч нужно описание с ключевыми словами (плотность не выше 7%), чтобы поисковик лучше оценил страницу

**Comment by dumbik** [comment]
вечером обсудим

**Comment by nikolayr1** [comment]
Условные обозначения:
$ProductName - название товара
$CategoryName[ip] – название категории текущего товара в иментительном патеже единственного числа
$CategoryName[rp] – название категории текущего товара в родительном патеже единственного числа
$CategoryName[vp] – название категории текущего товара в винительном патеже единственного числа

Meta_discription: Купить дешево $CategoryName[vp] $ProductName в Украине с бесплатной доставкой
Meta_keywords: Купить $CategoryName[ip], качественн(ый/ая) $CategoryName[ip], $CategoryName[ip] цена в Украине,
Description:(пока что одинаковое для всех категорий)
перед существующим или отсутствующем описанием товара дописываем следующие предложения:

0) В нашем (прекрасном / отличном / чудесном / невероятном / шикарном) интернем магазине rybolove.com. ua вы имеете возможность 
<b>купить эту/этот/это $CategoryName[vp] по саомой (лучшей / приемлимой) для Вас цене</b> с бесплатной(если $ItemPrice > 300грн) доставкой по всей Украине.
Для категорий катушки и удилища нужно первое слово названия категории поставить в конец, чтобы получилось 
"кастинговое удилище" вместо "удилище кастинговое"

1) (Представляем(Вашему вниманию/Вам))/Перед Вами) $ProductName
При построении предложения выражение в скобочках выбирается случайно. Первое предложение может иметь вид:
-Передставляем Вашему вниманию $ProductName
-Передставляем Вам $ProductName
-Перед Вами $ProductName
Это делается для того, чтобы увеличить уникальность текста описания товара.
Добавляйте или слова в скобочках или новые предложения на свое умотрение. Я привожу только пример возможного описания.

2а)Для $CategoryName женского рода(катушка, приманка, ):
Это (высококачественная / очень качественная / невероятная / отличная / превосходная / удивительная / чудесная) $CategoryName[ip]!
2б)Для $CategoryName мужского рода(поплавок, грузик ):
Это (высококачественный / очень качественный / невероятный / отличный / превосходный / удивительный / чудесный) $CategoryName[ip]!
2в)Для $CategoryName среднего рода(поплавок, грузик ):
Это (высококачественное / очень качественное / невероятное / отличное / превосходное / удивительное / чудесное) $CategoryName[ip]!

3)(Наверняка / Вероятно, что / Очевидно, что) каждый рыбакак (мечтает / хотел бы / хочет / желает) иметь эту/этот/это $CategoryName[ip]

4) Почему(же / -) так?(- спросите вы. / - )

5)(Это потому / Все из-за того / Конечно же потому), что производитель позаботился о качетстве этого/этой $CategoryName[rp]
и (сделале / произвел / создал)(настоящий / невероятный / фантастический / исключительный)(товар / продукт)

6) И именно поэтому $ProductName является (воистину / -)(прекрасным / непревзойденным / чудесным / выдающимся / дивным / волшебным) 
представителем своего семейства.

7) Лучшие рыбаки (всего мира / повсеместно / очень часто / всегда) с удовольствием используют данный продукт.



Пример результата description:
В нашем отличном интернет магазине rybolove.com. ua вы имеете возможность
купить это карповое удилище по самой лучшей для Вас цене с бесплатной доставкой по всей Украине.
Перед Вами спиннинговое удилище Mitchell Privilege Pro Tele 2,10m/6 8-25gr 126gr 24T/30T Carbon Cork SIC
Это превосходное спиннинговое удилище!
Вероятно, что каждый рыбак хочет иметь это спиннинговое удилище
Почему так? - спросите вы.
Все из-за того, что производитель позаботился о качестве этого спинингового удилища
И именно поэтому Mitchell Privilege Pro Tele 2,10m/6 8-25gr 126gr 24T/30T Carbon Cork SIC является 
воистину непревзойденным  представителем своего семейства.
Лучшие рыбаки всегда с удовольствием используют данный продукт.

Уникальность текста: 85% уже очень неплохо.
Длина 579 символов.

**Comment by dumbik** [comment]
сделано и залито

**Comment by nikolayr1** [comment]
1) название категории в тексте описания должно писаться с маленькой буквы. не Костюм, а костюм
2) купить эту/этот/это $CategoryName[vp] по саомой (лучшей / приемлимой) для Вас цене в теге b - жирный шрифт
3) поставить теги br для увеличения читабельности

**Comment by dumbik** [comment]
исправлено
