### ISSUE TITLE
Комментарии товаров

### ISSUE THREAD

**Issue by nikolayr1** [TopQualityGuys/rybolove#193]
1) Припилить возможность делать комментарии для товаров.
2) Откоментить товары скриптом по 0-5 комментариев. 
Комменты собрать из фраз типа:
"норм $productCategory. уже четвертый/третий/второй год/месяц/сезон пользуюсь"
"отличный/хороший товар за свою/эту цену"
"я доволен качеством/этим товаром"
... итд
Это увеличит уникальность страниц.

**Comment by dadakax** [comment]
возможность добавлять комменты припилена
