### ISSUE TITLE
Добавить функциональные блоки

### ISSUE THREAD

**Issue by nikolayr1** [TopQualityGuys/rybolove#194]
Добавить блоки "Похожие товары"
Такие функциональные блоки упростят навигацию по сайту (хорошо для пользователя) и увеличат уровень внутренней перелинковки страниц(хорошо для поискового бота)
еще можно добавить блоки:
-с этим часто покупают 
-комплекты
-лучшие товары этой категории
-аксессуары

**Comment by dadakax** [comment]
Чтоб добавить эту штуку нужно вручную для каждого товара выбирать похожие товары
типа так:
![image](https://cloud.githubusercontent.com/assets/8439283/8503210/4b06d32c-21c4-11e5-9991-d7e710397d92.png)

ну или писать свой модуль, который по каким-либо признакам будет выбирать похожие товары

**Comment by nikolayr1** [comment]
ок. пока прикроем.
