### ISSUE TITLE
Страница мои заказы адаптивная верстка до 24.05.2015 23.59

### ISSUE THREAD

**Issue by dadakax** [TopQualityGuys/rybolove#20]
![image](https://cloud.githubusercontent.com/assets/8439283/7746528/ae0f069a-ffbb-11e4-819c-95f650f06686.png)

**Comment by Wilvarin** [comment]
![image](https://cloud.githubusercontent.com/assets/11726090/7780941/68029282-00ee-11e5-8554-4e5b5bc6e588.png)
![image](https://cloud.githubusercontent.com/assets/11726090/7780942/6c6344de-00ee-11e5-9cd2-cefd36906c5a.png)
не могу понять как изменить этот синий фон в таблице. С версткой все ок
![image](https://cloud.githubusercontent.com/assets/11726090/7780950/8e85999a-00ee-11e5-81a9-f419e72eb466.png)
нужно менять стили в styles.css
![image](https://cloud.githubusercontent.com/assets/11726090/7780959/b129eac8-00ee-11e5-8004-8d20f33691b3.png)
я в замешательстве

**Comment by dadakax** [comment]
Оригинальный файл находится здесь C:\WebServers\home\rybolove\www\framework\zii\widgets\assets\gridview\styles.css
Проблема в том, что он кешируется, сохраняется в папках assests, поэтому изменений не видно. Чтобы что-то изменилось, удаляешь все папки из папки assets (кроме productThumbs), потом чистишь кеш в браузере, а уже потом обновляешь страницу

**Comment by Wilvarin** [comment]
![image](https://cloud.githubusercontent.com/assets/11726090/7783648/8733ad90-0151-11e5-8569-6e91b969df98.png)
![image](https://cloud.githubusercontent.com/assets/11726090/7783650/9a652984-0151-11e5-9ec6-9e690994f593.png)
Даш, если посчитаешь что эта задача выполнена то закрой )
