### ISSUE TITLE
меню.иконнки

### ISSUE THREAD

**Issue by dumbik** [TopQualityGuys/rybolove#200]
переделать главное меню - добавить к каждому полю иконку (типа каталог товаров - иконка каталога или списка какого-то, доставка и оплата - картинка грузовика какая-то или что-то такое, помощь - картинка SOS - нужно продумать - это скорее для Оли)

**Comment by Wilvarin** [comment]
да с картиночками менюшка лучше смотрится.

**Comment by nikolayr1** [comment]
![image](https://cloud.githubusercontent.com/assets/11279857/9338022/a45738ce-45f3-11e5-87d9-94421ba9976b.png)
