### ISSUE TITLE
слайдер брендов

### ISSUE THREAD

**Issue by dumbik** [TopQualityGuys/rybolove#201]
вставить какой-то покрасивее слайдер - можно из тех ссылочек с файла на ГД, который я добавил. там вроде были прикольные слайдеры. ну и + добавить вывод товаров по производителям (задача уже давно открыта)

**Comment by olleskiv** [comment]
Чего-то кардинально нового в дизайне я не могу придумать. Было бы интересно поставить авто-скроллинг http://www.gmarwaha.com/jquery/jcarousellite/demo.php . Можно к 
этому еще добавить скрол колесиком мыши
