### ISSUE TITLE
Картинки. каталог. 

### ISSUE THREAD

**Issue by successus** [TopQualityGuys/rybolove#218]
Увеличить уменьшеную копию картинок товаров, что отображаються в каталоге.

и в css
И в коде. Нужно проставить в параметрах.

**Comment by nikolayr1** [comment]
увеличить эти картинки что-ли? 
![image](https://cloud.githubusercontent.com/assets/11279857/9398667/9c1b18a6-47ba-11e5-821e-dc216340e8f2.png)

**Comment by successus** [comment]
так

**Comment by nikolayr1** [comment]
![image](https://cloud.githubusercontent.com/assets/11279857/9429659/e26615ce-49e8-11e5-85fb-f7e1f54c065b.png)
