### ISSUE TITLE
Фиксация меню

### ISSUE THREAD

**Issue by successus** [TopQualityGuys/rybolove#222]
Сделать, чтобы div с фильтрами и меню, прилипал к верху екрана

**Comment by nikolayr1** [comment]
Кнопочка товаров особо не влезает в менюшку, Стас. может не будем делать?
![image](https://cloud.githubusercontent.com/assets/11279857/9338519/31713a6e-45f6-11e5-9c4b-bd788b403066.png)

**Comment by nikolayr1** [comment]
ой, не туда
