### ISSUE TITLE
Два товара в ряд

### ISSUE THREAD

**Issue by successus** [TopQualityGuys/rybolove#223]
При горизонтальном положении екрана, выводить два товара в ряд.
А если это планшет, и влазит 3, то выводить 3

**Comment by nikolayr1** [comment]
а разве бутстрап не справляется? этого не происходит?

**Comment by successus** [comment]
@nikolayr1, перевір сам

**Comment by nikolayr1** [comment]
![screen shot 2015-09-05 at 22 42 19](https://cloud.githubusercontent.com/assets/11279857/9700943/c16b9a62-5427-11e5-94e7-03e8271a5685.png)
![screen shot 2015-09-05 at 22 42 10](https://cloud.githubusercontent.com/assets/11279857/9700944/c17380e2-5427-11e5-88ef-2fdc0c72fc60.png)
