### ISSUE TITLE
Дизайн.статические страници

### ISSUE THREAD

**Issue by successus** [TopQualityGuys/rybolove#224]
Придумать визуальную часть для стат страниц:
КАК СДЕЛАТЬ ЗАКАЗ, 
Можна ифнографику. или хотя бы, иконку трубки и скрин карточки товара и кнопки купить

ДОСТАВКА И ОПЛАТА, 
Картинку вставить, с автомобилем

ОБРАТНАЯ СВЯЗЬ,
Контактную форму вправо

 ГАРАНТИЯ, ПОМОЩЬ
Добавить картинки сертификатов, 
Галочки. знаки "Люкс"...

**Comment by olleskiv** [comment]
ГАРАНТИЯ, ПОМОЩЬ
Добавить картинки сертификатов, 
Галочки. знаки "Люкс"...

1)Где брать сертификаты?
2) Что еще за знаки "люкс"?

**Comment by dumbik** [comment]
Сертификаты производителей получается, типа что они классную продукцию производят.
На сайте производителя наверное))
