### ISSUE TITLE
Категория. Сортировка и загооловок

### ISSUE THREAD

**Issue by successus** [TopQualityGuys/rybolove#225]
Должно выгледить примерно так.

причем, последний пункт в хлебных крошках, это <h1>
![image](https://cloud.githubusercontent.com/assets/4658969/9036879/5f6cccee-39ee-11e5-8d1f-0106bec86e3f.png)

**Comment by nikolayr1** [comment]
я название категории <h1>Катушки</h1> оставлю для сео

**Comment by dumbik** [comment]
а на мобильной версии будет выглядеть так, как сейчас?

**Comment by nikolayr1** [comment]
нет, сейчас не очень качественно. я переделаю немного 
![image](https://cloud.githubusercontent.com/assets/11279857/9144703/b0e2f6ec-3d5f-11e5-8c8c-170f418277e4.png)

**Comment by dumbik** [comment]
ну я имел в виду чтобы оно отображалось так 
![image](https://cloud.githubusercontent.com/assets/11014944/9144742/ab36d34c-3d57-11e5-83d6-ffa21e4538df.png)
