### ISSUE TITLE
стоимость доставки

### ISSUE THREAD

**Issue by dumbik** [TopQualityGuys/rybolove#226]

**Comment by dumbik** [comment]
сделать нормальный вывод стоимости (30-35 грн).
![image](https://cloud.githubusercontent.com/assets/11014944/9044345/ae97b6a4-3a24-11e5-950c-3b4ec855bc33.png)

**Comment by nikolayr1** [comment]
поставил стоимость $1.6. Проверил - все работает. Для существующих заказов пересчета не будет
