### ISSUE TITLE
Пофиксить количество товаров на странице товара до 24.05.2015 23.59

### ISSUE THREAD

**Issue by dadakax** [TopQualityGuys/rybolove#23]
Сделать так, чтобы по умолчанию всегда была единичка в поле, плюс дописать где-то что это количество товаров, а то не понятно ничего.
![image](http://dl1.joxi.net/drive/0008/3393/531777/150521/02b735cdb1.jpg)

**Comment by Wilvarin** [comment]
если что огурчик это сделал но как обычно не запушил. 
так что не делайте второй раз.

**Comment by dadakax** [comment]
Скажи ему чтоб запушил)

**Comment by Wilvarin** [comment]
сказал что днем запушил

**Comment by dadakax** [comment]
![image](https://cloud.githubusercontent.com/assets/8439283/7785801/5c878c2a-01aa-11e5-8eb5-d4c65722e645.png)
Написать, что это именно количество товаров.
