### ISSUE TITLE
вывод картинок

### ISSUE THREAD

**Issue by dumbik** [TopQualityGuys/rybolove#232]
сделать нормальный вывод картинок. маленькие картинки хреново отображаются
![image](https://cloud.githubusercontent.com/assets/11014944/9245540/8f5bfd6e-41ad-11e5-935e-8e163208f445.png)

**Comment by dadakax** [comment]
Надо еще размер их поменять. Тех, что в папке ассетс, там размеры для старого шаблона вроде
