### ISSUE TITLE
исправить поиск при нуле и пустой строке 

### ISSUE THREAD

**Issue by dadakax** [TopQualityGuys/rybolove#233]
![image](https://cloud.githubusercontent.com/assets/8439283/9258498/89497bde-4204-11e5-87da-40ef45f9851c.png)
C:\xampp\htdocs\metalEximus\www\protected\modules\store\controllers\CategoryController.php
убрать if(!$q) $this->render('search');

**Comment by dadakax** [comment]
исправить при '/' и 0

**Comment by nikolayr1** [comment]
даша все поправила
