### ISSUE TITLE
Выводить сопутствующие товары

### ISSUE THREAD

**Issue by successus** [TopQualityGuys/rybolove#242]
Вернуть из шаблона на карточку товара блок "сопутствующие".

**Comment by dumbik** [comment]
импортим новую базу local-20-08-18-52.rar (там есть сопутствующие товары для одной катушки)
заходим на http://rybolove/product/katushka-s-baitranerom-abu-garcia-cardinal-fs-405i-free-runner-51-035190m-481-074m-440g-polymeric.html
