### ISSUE TITLE
Подправить верстку формы подписки на рассылку 

### ISSUE THREAD

**Issue by dadakax** [TopQualityGuys/rybolove#244]
![image](https://cloud.githubusercontent.com/assets/8439283/9291053/4956e4ec-43b4-11e5-866c-4e127d279091.png)

она теперь работает)

**Comment by nikolayr1** [comment]
![image](https://cloud.githubusercontent.com/assets/11279857/9337196/fb73d112-45ee-11e5-9f3d-414d9dcc90d8.png)
![image](https://cloud.githubusercontent.com/assets/11279857/9337199/01d8acd0-45ef-11e5-93ac-2bc21c8ba5b7.png)
![image](https://cloud.githubusercontent.com/assets/11279857/9337207/0b07c5fc-45ef-11e5-8eb5-61098b7eb1c3.png)
