### ISSUE TITLE
Популярные товары

### ISSUE THREAD

**Issue by nikolayr1** [TopQualityGuys/rybolove#251]
![image](https://cloud.githubusercontent.com/assets/11279857/9359129/89f3e006-46a0-11e5-8c66-428f79dbddd3.png)

**Comment by Wilvarin** [comment]
http://prntscr.com/86geib
на фтп.

**Comment by dumbik** [comment]
СРОЧНО
http://rybolove/product/katushka-s-baitranerom-abu-garcia-cardinal-fs-405i-free-runner-51-035190m-481-074m-440g-polymeric.html
![image](https://cloud.githubusercontent.com/assets/11014944/9388426/f9d8f78a-476d-11e5-921f-1478c0f7f095.png)
![image](https://cloud.githubusercontent.com/assets/11014944/9388436/0583a620-476e-11e5-8def-3c9520bd3061.png)

**Comment by dumbik** [comment]
чтобы тестить сопутствующие товары не забудьте заимпортить новую базу с названием local

**Comment by nikolayr1** [comment]
![image](https://cloud.githubusercontent.com/assets/11279857/9395134/a71709a8-479d-11e5-878f-111e027f0e17.png)
![image](https://cloud.githubusercontent.com/assets/11279857/9395141/ad2b093e-479d-11e5-9eb5-c13353d490c5.png)

**Comment by nikolayr1** [comment]
![image](https://cloud.githubusercontent.com/assets/11279857/9395441/956d818a-479f-11e5-98bb-264dbf9b6bb1.png)
