### ISSUE TITLE
кажется явно стоит уменьшить вертикальные отступы между товарами

### ISSUE THREAD

**Issue by dumbik** [TopQualityGuys/rybolove#257]
![image](https://cloud.githubusercontent.com/assets/11014944/9425852/6259e73e-492a-11e5-83f4-02deca130313.png)

**Comment by dumbik** [comment]
![image](https://cloud.githubusercontent.com/assets/11014944/9425851/5cd79504-492a-11e5-8ab6-cc3d269693b1.png)

**Comment by nikolayr1** [comment]
там еще нужно увеличить размеры картинок. я чет придумаю кароч.

**Comment by nikolayr1** [comment]
![Uploading image.png…]()
