### ISSUE TITLE
Мобильная версия шапки, меню и фильтров до 24.05.2015 23.59

### ISSUE THREAD

**Issue by dadakax** [TopQualityGuys/rybolove#26]
![image](https://cloud.githubusercontent.com/assets/8439283/7785007/07fd764e-0185-11e5-9b38-e959cd0b7872.png)

**Comment by dadakax** [comment]
![image](https://cloud.githubusercontent.com/assets/8439283/7783972/ef831a78-015d-11e5-8717-4d07b935b572.png)

**Comment by dadakax** [comment]
![image](https://cloud.githubusercontent.com/assets/8439283/7784822/073bcdb2-017d-11e5-9352-8ab6601f6589.png)

**Comment by dadakax** [comment]
и шапки 
![image](https://cloud.githubusercontent.com/assets/8439283/7785201/564b46ac-018d-11e5-841a-14dc22ca0d55.png)

**Comment by olleskiv** [comment]
шапка аналогично 
![320](https://cloud.githubusercontent.com/assets/11739563/7785241/99c9c1cc-018f-11e5-9b8c-04850c5b41d2.png)
