### ISSUE TITLE
Сверстать страницу "Гарантия"

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/rybolove#263]
Макет и копию изображения вставлю в диалог rybolove.com.ua
![guarantee](https://cloud.githubusercontent.com/assets/11739563/9700639/bf277092-5412-11e5-885f-58529833442b.jpg)
![1](https://cloud.githubusercontent.com/assets/11739563/9700642/ccd1d41c-5412-11e5-8893-9fc9de5821ce.png)

**Comment by nikolayr1** [comment]
да так, чтобы текстурные поля работалки в мозиле
