### ISSUE TITLE
шрифты и фон статических страничек

### ISSUE THREAD

**Issue by dumbik** [TopQualityGuys/rybolove#277]
стандартные шрифты ни о чем. фон - возможно нужно поставить такой же зеленый, как у нас, только с небольшой прозрачностью например.
![image](https://cloud.githubusercontent.com/assets/11014944/9722417/698feb2e-55b5-11e5-9597-32e322e7e1a6.png)

**Comment by olleskiv** [comment]
Не могу сказать, что с фоном совсем плохо, но если ставить фон, так везде. В каталоге это произведет массу проблем. Поэтому оставляем белый
![image](https://cloud.githubusercontent.com/assets/11739563/9770462/fbf38bd6-5738-11e5-97ef-a054912bfc5e.png)
![image](https://cloud.githubusercontent.com/assets/11739563/9770528/3f1b2fcc-5739-11e5-995c-5544d231d858.png)
