### ISSUE TITLE
Сверстать блок "Новости"

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/rybolove#282]
Предполагается, что "подробнее" будет выезжать снизу, как в популярных товарах.
Макет на ГД. https://drive.google.com/drive/folders/0B4jAsad7pIGXUWN0Skx3ZWczZTg
![default](https://cloud.githubusercontent.com/assets/11739563/9743498/6759c130-566f-11e5-9365-e2b2492e1934.png)
![image](https://cloud.githubusercontent.com/assets/11739563/9743493/61481f9e-566f-11e5-85c7-6d74ffe391ad.png)

**Comment by dumbik** [comment]
мне нравится дизайн. Оля, ты молодец)) надеюсь я не один такого мнения.
