### ISSUE TITLE
Нет картинки

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/rybolove#286]
Когда нет картинки лучше будет ставить такую заглушку. Какого размера картинку надо подготовить?
![- -1](https://cloud.githubusercontent.com/assets/11739563/9746542/2daab216-5681-11e5-9b62-31a22c360293.png)

**Comment by olleskiv** [comment]
или так)) 
![4](https://cloud.githubusercontent.com/assets/11739563/9746589/7c24a64a-5681-11e5-9d71-29338c3e8b6a.png)

**Comment by dumbik** [comment]
210x300, но можешь на всякий случай сбросить побольше, но примерно в таких же пропорциях.
идея реально классная)
