### ISSUE TITLE
Пагинация ломается в моб версии до 24.05.2015

### ISSUE THREAD

**Issue by dadakax** [TopQualityGuys/rybolove#29]
![image](https://cloud.githubusercontent.com/assets/8439283/7785219/49fc4620-018e-11e5-944e-b61a9abb0aae.png)

**Comment by Wilvarin** [comment]
![image](https://cloud.githubusercontent.com/assets/11726090/7785685/00fd7d02-01a4-11e5-945e-245aa2a99692.png)
![image](https://cloud.githubusercontent.com/assets/11726090/7785687/0d9cbbe0-01a4-11e5-8eea-7ae64d0627a6.png)
уже не ломается
