### ISSUE TITLE
Вернуть заголовкам Дециму

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/rybolove#296]
Короче, везде где она есть в макетах и в шаблоне
![image](https://cloud.githubusercontent.com/assets/11739563/9810267/0c4d98c4-5878-11e5-8ed7-fa75fa1495fe.png)
![image](https://cloud.githubusercontent.com/assets/11739563/9810271/137860c0-5878-11e5-9240-3eba24a81e74.png)
![image](https://cloud.githubusercontent.com/assets/11739563/9810283/27eddad0-5878-11e5-8d8f-7e461307b7dd.png)

**Comment by dumbik** [comment]
так лучше?
![image](https://cloud.githubusercontent.com/assets/11014944/9818160/b700cba6-58af-11e5-9c27-755bbef57f05.png)
