### ISSUE TITLE
подправить страницу категорий до 24.05.2015

### ISSUE THREAD

**Issue by dadakax** [TopQualityGuys/rybolove#30]
страница категории чуть-чуть ломается от 550рх до 620рх и от 840 до 895рх
![image](https://cloud.githubusercontent.com/assets/8439283/7785307/1d1fe378-0193-11e5-9d8f-1861ad9e4a7b.png)
![image](https://cloud.githubusercontent.com/assets/8439283/7785311/6564b41a-0193-11e5-858f-1c894d09b1af.png)

**Comment by dadakax** [comment]
все по ширине блока
![image](https://cloud.githubusercontent.com/assets/8439283/7785317/b0f36b92-0193-11e5-8692-0fffcc9f2e0b.png)

**Comment by Wilvarin** [comment]
готово, запушено
