### ISSUE TITLE
страница оформления заказа очень странная до 24.05.2015 23.59

### ISSUE THREAD

**Issue by dadakax** [TopQualityGuys/rybolove#32]
![image](https://cloud.githubusercontent.com/assets/8439283/7785793/1e523248-01aa-11e5-9599-103a3cbc2a3a.png)

**Comment by dadakax** [comment]
Спасибо, ваш заказ принят

**Comment by dumbik** [comment]
![image](https://cloud.githubusercontent.com/assets/11014944/7787895/5dd67fe6-022c-11e5-87f3-92352613a3a6.png)
