### ISSUE TITLE
Первая страница

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/rybolove#36]
сторона малого квадрата 325, большого 650

![6](https://cloud.githubusercontent.com/assets/11739563/7788621/8783f07a-024b-11e5-9ada-69a6c5b2df43.png)

**Comment by olleskiv** [comment]
![1](https://cloud.githubusercontent.com/assets/11739563/7788653/52f02166-024c-11e5-9b5d-7c3ab6ac9860.png)
![2](https://cloud.githubusercontent.com/assets/11739563/7788649/52eee490-024c-11e5-849c-848c30cd89f1.png)
![3](https://cloud.githubusercontent.com/assets/11739563/7788650/52eeff52-024c-11e5-8569-159babe73bd7.png)
![4](https://cloud.githubusercontent.com/assets/11739563/7788651/52ef8166-024c-11e5-9452-f7b68e0b2a51.png)
![5](https://cloud.githubusercontent.com/assets/11739563/7788652/52f007f8-024c-11e5-98ea-a4685109352e.png)

**Comment by olleskiv** [comment]
![2](https://cloud.githubusercontent.com/assets/11739563/7788667/0c9cd8ac-024d-11e5-8ff1-5ff097e1c8f7.png)
![3](https://cloud.githubusercontent.com/assets/11739563/7788666/0c9c33b6-024d-11e5-9981-36b9757a6fae.png)
![4](https://cloud.githubusercontent.com/assets/11739563/7788665/0c9bed48-024d-11e5-8bec-592b12af30aa.png)
![5](https://cloud.githubusercontent.com/assets/11739563/7788669/0c9ed7c4-024d-11e5-8b6d-472610d5c795.png)
![6](https://cloud.githubusercontent.com/assets/11739563/7788668/0c9d91ac-024d-11e5-9479-8ec0413d1263.png)
![7](https://cloud.githubusercontent.com/assets/11739563/7788670/0c9eed68-024d-11e5-93e1-d83f9ff4f94e.png)
![-3](https://cloud.githubusercontent.com/assets/11739563/7788671/0cb6403a-024d-11e5-8455-f037690d578c.png)

**Comment by olleskiv** [comment]
Добавила Поиск: цвет рамки dddddd, ширина кнопки "поиск" 100 пикс, отступ от логотипа 50 пикселей  
![7](https://cloud.githubusercontent.com/assets/11739563/7788704/507d1c38-024f-11e5-96a6-8fbc56e6119b.png)

**Comment by olleskiv** [comment]
лого
![default](https://cloud.githubusercontent.com/assets/11739563/7788718/5b2a689c-0250-11e5-8bf7-9dd72c89210d.png)

**Comment by dadakax** [comment]
рабочая корзина

**Comment by dadakax** [comment]
фильтры на фотках

**Comment by olleskiv** [comment]
Расположение лого в футере. Размер 130х
![default](https://cloud.githubusercontent.com/assets/11739563/7897974/bf62047a-06f9-11e5-9d8c-609b4ee62c9b.png)
![2](https://cloud.githubusercontent.com/assets/11739563/7897973/bf613f0e-06f9-11e5-8331-6748a85e552e.png)

53

**Comment by olleskiv** [comment]
обновить картинки на странице 
![1](https://cloud.githubusercontent.com/assets/11739563/7898202/27023350-0701-11e5-8c82-2638a1970122.png)
![2](https://cloud.githubusercontent.com/assets/11739563/7898205/2702fa60-0701-11e5-904a-a95c1961cc42.png)
![3](https://cloud.githubusercontent.com/assets/11739563/7898204/2702eb74-0701-11e5-8fe0-c37867bc077f.png)
![4](https://cloud.githubusercontent.com/assets/11739563/7898203/27028b16-0701-11e5-994f-fd8c7ace61a0.png)
