### ISSUE TITLE
Каталог товаров

### ISSUE THREAD

**Issue by dumbik** [TopQualityGuys/rybolove#50]
Сделать дизайн страницы

**Comment by olleskiv** [comment]
![default](https://cloud.githubusercontent.com/assets/11739563/7970076/38442c18-0a44-11e5-80e2-db6f34459cbd.png)
![default](https://cloud.githubusercontent.com/assets/11739563/7970082/42846594-0a44-11e5-87da-44f7d835e994.png)
![default](https://cloud.githubusercontent.com/assets/11739563/7970086/428be850-0a44-11e5-9c8c-69e90c63c0b4.png)
![default](https://cloud.githubusercontent.com/assets/11739563/7970084/428ba408-0a44-11e5-8cbd-5af5b6260d3c.png)
![default](https://cloud.githubusercontent.com/assets/11739563/7970083/428b7406-0a44-11e5-81a5-b94546a8616d.png)
![default](https://cloud.githubusercontent.com/assets/11739563/7970085/428bc712-0a44-11e5-831c-142f1ec9a5a9.png)
![default](https://cloud.githubusercontent.com/assets/11739563/7970087/428cb42e-0a44-11e5-8cf0-6c518a07ff5d.png)
![3](https://cloud.githubusercontent.com/assets/11739563/7970088/429d13f0-0a44-11e5-8649-423d93ca6246.png)
![default](https://cloud.githubusercontent.com/assets/11739563/7970090/42a49698-0a44-11e5-9458-558355b707ac.png)
![default](https://cloud.githubusercontent.com/assets/11739563/7970089/42a46290-0a44-11e5-9667-92742528400c.png)
![default](https://cloud.githubusercontent.com/assets/11739563/7970091/42a5a47a-0a44-11e5-9976-d29b9e0d435d.png)
