### ISSUE TITLE
Сверстать картинки для главного слайдера (2 слайда) (цыпочки!!!)

### ISSUE THREAD

**Issue by dumbik** [TopQualityGuys/rybolove#52]
тут все понятно

**Comment by olleskiv** [comment]
Подкорректировать высоту блока ![-1](https://cloud.githubusercontent.com/assets/11739563/7966296/d4e85b02-0a2b-11e5-9c4d-afd9df7afe66.png)

**Comment by olleskiv** [comment]
2-я картинка слайдера
![1234](https://cloud.githubusercontent.com/assets/11739563/7966331/0d4476b6-0a2c-11e5-928a-5948233ab313.png)
![4](https://cloud.githubusercontent.com/assets/11739563/7966330/0d42a5ca-0a2c-11e5-941c-3528d7700d81.png)
![3](https://cloud.githubusercontent.com/assets/11739563/7966332/0d45158a-0a2c-11e5-804c-5a813390ac44.png)
![2](https://cloud.githubusercontent.com/assets/11739563/7966334/0d467ad8-0a2c-11e5-9097-cb3829361c79.png)
![1](https://cloud.githubusercontent.com/assets/11739563/7966333/0d45dd26-0a2c-11e5-8502-10f6b9a74930.png)

**Comment by olleskiv** [comment]
3-я картинка в слайдере
![1234](https://cloud.githubusercontent.com/assets/11739563/7966314/ef160e66-0a2b-11e5-95bf-2aa91eca3b1b.png)
![1](https://cloud.githubusercontent.com/assets/11739563/7966315/ef1620b8-0a2b-11e5-974e-9e3dd1d1482a.png)
![2](https://cloud.githubusercontent.com/assets/11739563/7966313/ef15b042-0a2b-11e5-9560-d20f96fb0027.png)
![3](https://cloud.githubusercontent.com/assets/11739563/7966316/ef16967e-0a2b-11e5-980c-97cd7628a407.png)
![4](https://cloud.githubusercontent.com/assets/11739563/7966317/ef190242-0a2b-11e5-9e85-c7c3298555c8.png)
