### ISSUE TITLE
Poup-up - окно!Добавить!

### ISSUE THREAD

**Issue by AndruAlex** [TopQualityGuys/rybolove#63]
Взять старое или написать новое попап окно!при добавлении товара !

**Comment by AndruAlex** [comment]
http://sitear.ru/material/jquery-popup-okno

**Comment by dadakax** [comment]
![image](https://cloud.githubusercontent.com/assets/8439283/8013141/8f7070e6-0bcf-11e5-80d7-baa16894cfb4.png)
