### ISSUE TITLE
Доделать страницу оформленного заказа

### ISSUE THREAD

**Issue by dumbik** [TopQualityGuys/rybolove#64]

**Comment by olleskiv** [comment]
![default](https://cloud.githubusercontent.com/assets/11739563/7985324/9c207d88-0ad8-11e5-8b52-9b715b2b1716.png)

**Comment by olleskiv** [comment]
![default](https://cloud.githubusercontent.com/assets/11739563/7985369/f5413b0a-0ad8-11e5-833a-ef0e8a7eb271.png)
