### ISSUE TITLE
Страница поиска

### ISSUE THREAD

**Issue by successus** [TopQualityGuys/rybolove#69]
Верстку нужно такую же как в каталоге товаров.

http://rybolove/products/search/q/%D0%BA%D0%B0%D1%82%D1%83%D1%88%D0%BA%D0%B0

**Comment by dadakax** [comment]
![image](https://cloud.githubusercontent.com/assets/8439283/8011447/778be0a4-0bc1-11e5-9c75-dabdc969a24e.png)
