### ISSUE TITLE
сделать адаптивный слайдер в хедере

### ISSUE THREAD

**Issue by dumbik** [TopQualityGuys/rybolove#70]

**Comment by dumbik** [comment]
![image](https://cloud.githubusercontent.com/assets/11014944/7915353/aabbc0dc-0885-11e5-8433-629cdf578c35.png)

**Comment by olleskiv** [comment]
![1](https://cloud.githubusercontent.com/assets/11739563/7987464/547184a6-0ae6-11e5-85f8-78fff3e948ea.png)
![2](https://cloud.githubusercontent.com/assets/11739563/7987467/54775a52-0ae6-11e5-884f-acbd327bf633.png)
![3](https://cloud.githubusercontent.com/assets/11739563/7987465/54750932-0ae6-11e5-9f48-b6d4552d7f72.png)
![4](https://cloud.githubusercontent.com/assets/11739563/7987466/5475b2d8-0ae6-11e5-9ea2-a974b2d08b11.png)

**Comment by olleskiv** [comment]
![1](https://cloud.githubusercontent.com/assets/11739563/7987906/24da7b8c-0ae9-11e5-9564-9aab4c81b8b3.png)
![2](https://cloud.githubusercontent.com/assets/11739563/7987908/24dba7fa-0ae9-11e5-8f7c-a057970e334b.png)
![3](https://cloud.githubusercontent.com/assets/11739563/7987907/24db46e8-0ae9-11e5-9a6e-3d73783aeabb.png)
![4](https://cloud.githubusercontent.com/assets/11739563/7987905/24d8a5a0-0ae9-11e5-8048-153350d12ceb.png)

**Comment by olleskiv** [comment]
![1](https://cloud.githubusercontent.com/assets/11739563/7988058/0c16db9e-0aea-11e5-8abf-a411ad1ddb71.png)
![2](https://cloud.githubusercontent.com/assets/11739563/7988059/0c1be18e-0aea-11e5-9ea8-f62a61203b1a.png)
![3](https://cloud.githubusercontent.com/assets/11739563/7988060/0c1cd44a-0aea-11e5-9c21-e9d877d68fe8.png)
![4](https://cloud.githubusercontent.com/assets/11739563/7988061/0c1c509c-0aea-11e5-9b96-a07a0f265342.png)

**Comment by olleskiv** [comment]
![1](https://cloud.githubusercontent.com/assets/11739563/7988957/ecffb3d4-0aee-11e5-80ca-0e206f573536.png)
![2](https://cloud.githubusercontent.com/assets/11739563/7988958/ed159fa0-0aee-11e5-9cc3-69769990ee20.png)
![3](https://cloud.githubusercontent.com/assets/11739563/7988959/ed27d454-0aee-11e5-9201-34840cebf050.png)
![4](https://cloud.githubusercontent.com/assets/11739563/7988960/ed2b50ac-0aee-11e5-8ef0-ef8507f90ce1.png)
