### ISSUE TITLE
придумать эффект при наведении на блок категории

### ISSUE THREAD

**Issue by dumbik** [TopQualityGuys/rybolove#73]
![image](https://cloud.githubusercontent.com/assets/11014944/7986508/9d8e2dac-0ae0-11e5-803e-0f5a11c5ad24.png)

**Comment by nikolayr1** [comment]
пока что поставил hover

**Comment by nikolayr1** [comment]
и пока этого достаточно

**Comment by nikolayr1** [comment]
и курсор поинтер еще
