### ISSUE TITLE
Добавить кнопки "мне нравится" и "добавить товар к сравнению"

### ISSUE THREAD

**Issue by nikolayr1** [TopQualityGuys/rybolove#81]
Нужен шаблон!
Где они будут находиться?

**Comment by dumbik** [comment]
Уверены, что они нужны?
Мы это уже обсуждали. Товары к сравнению - абсолютно бесполезная, а точнее бессмысленная шутка в нашем случае. У нас нет отдельных параметров у товаров, чтобы их можно было сравнивать. Для этого нужна намного сложнее архитектура БД, для каждого типа товаров нужна отдельная таблица, где будут параметры и их значения. Можешшь зайти на hotline.ua и глянуть, о чем я говорю. Так что предлагаю эту задачу закрыть.

**Comment by Wilvarin** [comment]
вполне разумное замечание.

**Comment by nikolayr1** [comment]
согласен

**Comment by dumbik** [comment]
Короче. я закрываю задачу. Если будут аргументы, чтобы ее открыть - пожалуйста.

**Comment by dadakax** [comment]
про архитектуру бд бред, у нас можно добавлять всякие параметры для товаров, мы просто при импорте этого не делали

**Comment by dumbik** [comment]
Пф, сама ты бред) смысл моих слов в большей мере заключался в том, что
чтобы сделать сравнение товаров, придется попотеть. И там нужна будет и
участь Коли-рыбака возможно, чтобы он говорил, по каким параметрам что
сравнивать. У нас УГ описания товаров, поверьте мне как человеку, который
целый год занимался сбором технических характеристик товаров. У нас почти
4к товаров, а реально сравнивать мы можем только катушки. На этом тему
можно закрывать.

14 июня 2015 г., 7:39 пользователь Daria <notifications@github.com> написал:
