### ISSUE TITLE
Футер. Шрифты и рассылка

### ISSUE THREAD

**Issue by dadakax** [TopQualityGuys/rybolove#82]
починить шрифты и убрать блок с рассылкой
![image](https://cloud.githubusercontent.com/assets/8439283/8011375/e7caaa5e-0bc0-11e5-913d-1164c549826e.png)

**Comment by nikolayr1** [comment]
поменял шрифты

**Comment by AndruAlex** [comment]
блок с рассылкой вообще убрать?

**Comment by dadakax** [comment]
да
