### ISSUE TITLE
Уменьшить расстояние

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/rybolove#92]
пикселей на 20 и сверху и снизу (а лучше в скайпе позвонить и вместе решим на сколько)
![13](https://cloud.githubusercontent.com/assets/11739563/8012289/f2b2ba80-0bc8-11e5-9d13-02b84e1f1e89.png)

**Comment by olleskiv** [comment]
то же самое
![image](https://cloud.githubusercontent.com/assets/11739563/8012303/0f50d712-0bc9-11e5-9962-3197118e6a0c.png)

**Comment by Wilvarin** [comment]
саня сделал
