### ISSUE TITLE
Каталог товаров уменьшить расстояние

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/rybolove#94]
![15](https://cloud.githubusercontent.com/assets/11739563/8012425/1391583c-0bca-11e5-9a4b-272e3e1dfc63.png)

**Comment by Wilvarin** [comment]
+

**Comment by Wilvarin** [comment]
на странице товара сделал так же 
![image](https://cloud.githubusercontent.com/assets/11726090/8014759/f755e6f8-0bdb-11e5-8207-922a27f5ca5f.png)
